# Generated by Django 3.1.6 on 2021-12-05 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_user_initial_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='initial_money',
        ),
        migrations.RemoveField(
            model_name='user',
            name='initial_money',
        ),
    ]
